# Usage:
# docker-compose up -d --force-recreate
version: "3.4"

services:

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    ports:
      - 80:80
    environment:
      - ZALENIUM_HOST=zalenium.local # Add real domain and update your DNS records
      - JENKINS_HOST=jenkins.local # Add real domain and update your DNS records
      - NGINX_PORT=80
      - ZALENIUM_CONTAINER_NAME=zalenium
      - JENKINS_CONTAINER_NAME=jenkins
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - zalenium

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home # Use different location as tmp will be cleared after each system restart
    ports:
      - 8080:8080
    networks:
      - zalenium

  zalenium:
    image: dosel/zalenium:latest
    restart: always
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos # Use different location as tmp will be cleared after each system restart
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker # You can comment this if you running on Mac OS X
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 1440 --screenHeight 810
            --timeZone "Europe/Sarajevo"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --debugEnabled false
            --keepOnlyFailedTests false
            --maxTestSessions 4
    environment:
      - HOST_UID
      - HOST_GID
    networks:
      - zalenium

networks:
  zalenium:
    driver: bridge